// Dispatched action type criteria
const GET_ERRORS = 'GET_ERRORS';
const SET_CURRENT_BROTHER = 'SET_CURRENT_BROTHER';
const REGISTER_BROTHER = 'REGISTER_BROTHER';
const EDIT_BROTHER = 'EDIT_BROTHER';

const MERIT_PLEDGE = 'MERIT_PLEDGE';
const DISPATCH_REQUEST = 'DISPATCH_REQUEST';
const DELETE_REQUEST = 'DELETE_REQUEST';

export {
  GET_ERRORS,
  SET_CURRENT_BROTHER,
  REGISTER_BROTHER,
  EDIT_BROTHER,
  MERIT_PLEDGE,
  DISPATCH_REQUEST,
  DELETE_REQUEST,
};
