// Dispatched action type criteria
const GET_ERRORS = 'GET_ERRORS';
const SET_CURRENT_BROTHER = 'SET_CURRENT_BROTHER';
const REGISTER_BROTHER = 'REGISTER_BROTHER';

export { GET_ERRORS, SET_CURRENT_BROTHER, REGISTER_BROTHER };
